// Generated from the official Qualipool IDX -> SwissRETS mapping sheet
// (docs/FAQ.md of qualipool/swissrets links the source spreadsheet).
// JSON-track mapping: utilization columns are intentionally omitted because
// SwissRETS JSON 3.x removed utilizations. Regenerate rather than hand-edit.
import type { ObjectCategory } from '../idx/types';

export interface SwissRetsCategoryMapping {
  /** SwissRETS category slugs, main category first. Empty = no mapping (drop). */
  categories: string[];
  /** Characteristic to set to 'applies' alongside the categories, if any. */
  characteristic: string | null;
}

const MAP: Record<string, SwissRetsCategoryMapping> = {
  'AGRI/1': { categories: [], characteristic: null },
  'AGRI/2': { categories: [], characteristic: null },
  'AGRI/3': { categories: [], characteristic: null },
  'APPT/1': { categories: ['apartment'], characteristic: null },
  'APPT/2': { categories: ['apartment', 'maisonette'], characteristic: null },
  'APPT/3': { categories: ['apartment', 'attic-flat'], characteristic: null },
  'APPT/4': { categories: ['apartment', 'roof-flat'], characteristic: null },
  'APPT/5': { categories: ['apartment', 'one-room-flat'], characteristic: null },
  'APPT/6': { categories: ['apartment', 'one-room-flat'], characteristic: null },
  'APPT/7': { categories: ['apartment', 'furnished-flat'], characteristic: null },
  'APPT/8': { categories: ['apartment', 'stepped-flat'], characteristic: null },
  'APPT/9': { categories: ['apartment', 'granny-flat'], characteristic: null },
  'APPT/10': { categories: ['apartment', 'loft'], characteristic: null },
  'APPT/11': { categories: ['apartment', 'roof-flat'], characteristic: null },
  'GARDEN/0': { categories: [], characteristic: null },
  'GASTRO/1': { categories: ['hotel'], characteristic: null },
  'GASTRO/2': { categories: ['restaurant'], characteristic: null },
  'GASTRO/3': { categories: ['cafe'], characteristic: null },
  'GASTRO/4': { categories: ['bar'], characteristic: null },
  'GASTRO/5': { categories: [], characteristic: null },
  'GASTRO/6': { categories: [], characteristic: null },
  'GASTRO/7': { categories: [], characteristic: null },
  'GASTRO/8': { categories: [], characteristic: null },
  'GASTRO/9': { categories: [], characteristic: null },
  'GASTRO/10': { categories: [], characteristic: null },
  'GASTRO/11': { categories: [], characteristic: null },
  'GASTRO/12': { categories: [], characteristic: null },
  'GASTRO/13': { categories: [], characteristic: null },
  'GASTRO/14': { categories: [], characteristic: null },
  'GASTRO/15': { categories: [], characteristic: null },
  'GASTRO/16': { categories: [], characteristic: null },
  'GASTRO/17': { categories: ['bar'], characteristic: null },
  'HOUSE/1': { categories: ['detached-house'], characteristic: null },
  'HOUSE/2': { categories: ['row-house'], characteristic: null },
  'HOUSE/3': { categories: ['duplex-house'], characteristic: null },
  'HOUSE/4': { categories: ['stepped-house'], characteristic: null },
  'HOUSE/5': { categories: ['villa'], characteristic: null },
  'HOUSE/6': { categories: ['farm-house'], characteristic: null },
  'HOUSE/7': { categories: ['multiplex-house'], characteristic: null },
  'HOUSE/9': { categories: ['earth-sheltered-dwelling'], characteristic: null },
  'HOUSE/10': { categories: ['castle'], characteristic: null },
  'HOUSE/11': { categories: ['stoeckli'], characteristic: null },
  'HOUSE/12': { categories: ['chalet'], characteristic: null },
  'HOUSE/13': { categories: ['rustico'], characteristic: null },
  'INDUS/1': { categories: ['office'], characteristic: null },
  'INDUS/2': { categories: ['retail-location'], characteristic: null },
  'INDUS/3': { categories: [], characteristic: null },
  'INDUS/4': { categories: [], characteristic: null },
  'INDUS/5': { categories: [], characteristic: null },
  'INDUS/6': { categories: ['doctors-office'], characteristic: null },
  'INDUS/7': { categories: [], characteristic: null },
  'INDUS/8': { categories: [], characteristic: null },
  'INDUS/9': { categories: [], characteristic: null },
  'INDUS/10': { categories: ['car-repair-shop'], characteristic: null },
  'INDUS/11': { categories: [], characteristic: null },
  'INDUS/12': { categories: [], characteristic: null },
  'INDUS/13': { categories: [], characteristic: null },
  'INDUS/14': { categories: [], characteristic: null },
  'INDUS/15': { categories: [], characteristic: null },
  'INDUS/16': { categories: [], characteristic: null },
  'INDUS/17': { categories: [], characteristic: null },
  'INDUS/18': { categories: [], characteristic: null },
  'INDUS/19': { categories: ['atelier'], characteristic: null },
  'INDUS/20': { categories: [], characteristic: null },
  'INDUS/21': { categories: [], characteristic: null },
  'INDUS/22': { categories: [], characteristic: null },
  'INDUS/23': { categories: [], characteristic: null },
  'INDUS/24': { categories: [], characteristic: null },
  'INDUS/25': { categories: [], characteristic: null },
  'INDUS/26': { categories: [], characteristic: null },
  'INDUS/27': { categories: [], characteristic: null },
  'INDUS/28': { categories: ['workshop'], characteristic: null },
  'INDUS/29': { categories: [], characteristic: null },
  'INDUS/30': { categories: [], characteristic: null },
  'INDUS/31': { categories: [], characteristic: null },
  'INDUS/32': { categories: [], characteristic: null },
  'INDUS/33': { categories: [], characteristic: null },
  'INDUS/34': { categories: [], characteristic: null },
  'INDUS/35': { categories: [], characteristic: null },
  'INDUS/36': { categories: [], characteristic: null },
  'INDUS/37': { categories: [], characteristic: null },
  'INDUS/38': { categories: [], characteristic: null },
  'PARK/1': { categories: [], characteristic: 'isUnderRoof = does-not-apply' },
  'PARK/2': { categories: [], characteristic: 'isUnderRoof = applies' },
  'PARK/3': { categories: [], characteristic: 'hasGarage = applies' },
  'PARK/4': { categories: [], characteristic: 'hasGarageDouble = applies' },
  'PARK/5': { categories: [], characteristic: 'hasGarageUnderground = applies' },
  'PARK/7': { categories: [], characteristic: null },
  'PARK/8': { categories: [], characteristic: null },
  'PARK/9': { categories: [], characteristic: 'isUnderRoof = applies' },
  'PARK/10': { categories: [], characteristic: 'isUnderRoof = does-not-apply' },
  'PARK/11': { categories: [], characteristic: null },
  'PARK/12': { categories: [], characteristic: null },
  'PROP/1': { categories: [], characteristic: null },
  'PROP/2': { categories: [], characteristic: null },
  'PROP/3': { categories: [], characteristic: null },
  'PROP/4': { categories: [], characteristic: null },
  'SECONDARY/0': { categories: ['hobby-room'], characteristic: null },
  'SECONDARY/1': { categories: [], characteristic: null },
  'SECONDARY/2': { categories: [], characteristic: null },
};

export function swissRetsCategoriesFor(
  category: ObjectCategory,
  objectType: number | null,
): SwissRetsCategoryMapping {
  if (objectType == null) return { categories: [], characteristic: null };
  return MAP[`${category}/${objectType}`] ?? { categories: [], characteristic: null };
}
