import { useCallback, useEffect, useRef, useState } from 'react';
import { AlertTriangle, Check, Copy, Download, FileText } from 'lucide-react';
import { userManager } from '@aireon/shared';
import { useI18n } from '../../contexts/I18nContext';
import { signal } from '../../lib/signal';
import { CURRENT_VERSION } from '../../data/releaseMeta';
import { prepareListingImages } from '../../lib/idx/imagePrep';
import { buildIdxPackage, buildUnloadBytes } from '../../lib/idx/package';
import { buildIdxFields, serializeUnload, type BuildRecordOptions } from '../../lib/idx/record';
import type { IdxIssue, ListingDraft } from '../../lib/idx/types';

/**
 * Bearer header for the RES image host. Same id_token-first rule as
 * `imageService.getAuthToken`, but non-throwing: a missing session just means
 * the fetch goes out unauthenticated and the image lands in `failedFilenames`.
 */
async function getAuthHeader(): Promise<string | null> {
  try {
    const user = await userManager.getUser();
    if (!user || user.expired) return null;
    const token = user.id_token || user.access_token;
    return token ? `Bearer ${token}` : null;
  } catch {
    return null;
  }
}

/** Plain-text note shipped inside the ZIP so whoever opens it on the portal
 *  side knows what the folders are and how a full load behaves. */
function buildReadme(senderId: string, stamp: Date): string {
  return [
    'IDX 3.01 portal package',
    `Generated by: ${senderId}`,
    `Generated at: ${stamp.toISOString()}`,
    '',
    'data/unload.txt   One listing record per line, ISO-8859-1, "#" delimited,',
    '                  183 fields, CRLF line endings.',
    'images/           JPEG images referenced by the record, in listing order.',
    '',
    'Upload both folders with your own portal credentials (SMG/homegate FTP,',
    'the newhome import interface, or Flatfox). A full load REPLACES every ad',
    'previously published through this interface.',
    '',
  ].join('\n');
}

function triggerDownload(blob: Blob, filename: string, keep: (url: string) => void) {
  const url = URL.createObjectURL(blob);
  keep(url);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
}

interface ExportPanelProps {
  draft: ListingDraft;
  issues: IdxIssue[];
}

/**
 * The three export actions: the full ZIP package, a bare unload.txt, and a
 * clipboard copy of the single record. Errors block the two downloads (a
 * portal would reject the file); the copy stays available for inspection.
 */
export default function ExportPanel({ draft, issues }: ExportPanelProps) {
  const { t } = useI18n();
  const [busy, setBusy] = useState<'package' | 'unload' | null>(null);
  const [copied, setCopied] = useState(false);
  const [failedNames, setFailedNames] = useState<string[]>([]);
  const [error, setError] = useState(false);
  // The most recent object URL, revoked before the next export and on unmount
  // so a long session does not leak multi-megabyte blobs.
  const objectUrlRef = useRef<string | null>(null);
  const copyTimerRef = useRef<ReturnType<typeof setTimeout>>();

  useEffect(
    () => () => {
      if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);
      if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
    },
    [],
  );

  const keepUrl = useCallback((url: string) => {
    if (objectUrlRef.current) URL.revokeObjectURL(objectUrlRef.current);
    objectUrlRef.current = url;
  }, []);

  const recordOptions = (): BuildRecordOptions => ({
    senderId: `Aireon Showroom v${CURRENT_VERSION}`,
    lastModified: new Date(),
  });

  const baseName = draft.refProperty.trim() || 'listing';
  const blocked = issues.some((i) => i.severity === 'error');

  const downloadPackage = useCallback(async () => {
    setBusy('package');
    setError(false);
    setFailedNames([]);
    try {
      const opts = recordOptions();
      const { prepared, failedFilenames } = await prepareListingImages(draft.images, getAuthHeader);
      const unload = buildUnloadBytes(draft, opts);
      const blob = buildIdxPackage({
        unload,
        images: prepared,
        readme: buildReadme(opts.senderId, opts.lastModified),
      });
      triggerDownload(blob, `idx-package-${baseName}.zip`, keepUrl);
      setFailedNames(failedFilenames);
      void signal.send('Generate IDX Package', {
        metaData: {
          images: draft.images.length,
          category: draft.category,
          offer: draft.offerType,
        },
      });
    } catch {
      setError(true);
    } finally {
      setBusy(null);
    }
  }, [draft, baseName, keepUrl]);

  const downloadUnload = useCallback(() => {
    setBusy('unload');
    setError(false);
    try {
      const bytes = buildUnloadBytes(draft, recordOptions());
      const blob = new Blob([bytes as BlobPart], { type: 'text/plain' });
      triggerDownload(blob, 'unload.txt', keepUrl);
      void signal.send('Download IDX Unload', {
        metaData: { category: draft.category, offer: draft.offerType },
      });
    } catch {
      setError(true);
    } finally {
      setBusy(null);
    }
  }, [draft, keepUrl]);

  const copyRecord = useCallback(() => {
    const text = serializeUnload([buildIdxFields(draft, recordOptions())]);
    void navigator.clipboard
      ?.writeText(text)
      .then(() => {
        setCopied(true);
        if (copyTimerRef.current) clearTimeout(copyTimerRef.current);
        copyTimerRef.current = setTimeout(() => setCopied(false), 2000);
      })
      .catch(() => setError(true));
    void signal.send('Copy IDX Record', {
      metaData: { category: draft.category, offer: draft.offerType },
    });
  }, [draft]);

  const primaryDisabled = blocked || busy !== null;

  return (
    <section className="surface rounded-2xl p-4">
      <h2 className="mb-2.5 text-xs font-semibold uppercase tracking-wider text-gray-400">
        {t('page.publish.export.title')}
      </h2>

      <div className="space-y-2">
        <button
          type="button"
          onClick={() => void downloadPackage()}
          disabled={primaryDisabled}
          className={`inline-flex h-9 w-full items-center justify-center gap-1.5 rounded-lg px-3.5 text-xs font-semibold transition-colors focus-ring ${
            primaryDisabled
              ? 'cursor-not-allowed border border-white/5 bg-white/[0.02] text-gray-600'
              : 'border border-cyan-400/40 bg-cyan-500/15 text-cyan-200 hover:border-cyan-300/60 hover:bg-cyan-500/25'
          }`}
        >
          <Download size={13} aria-hidden="true" />
          {busy === 'package'
            ? t('page.publish.export.preparing', { total: draft.images.length })
            : t('page.publish.export.package')}
        </button>

        <button
          type="button"
          onClick={downloadUnload}
          disabled={primaryDisabled}
          className={`inline-flex h-9 w-full items-center justify-center gap-1.5 rounded-lg border px-3.5 text-xs font-semibold transition-colors focus-ring ${
            primaryDisabled
              ? 'cursor-not-allowed border-white/5 bg-white/[0.02] text-gray-600'
              : 'border-white/10 text-gray-300 hover:border-cyan-500/40 hover:bg-cyan-500/10 hover:text-cyan-300'
          }`}
        >
          <FileText size={13} aria-hidden="true" />
          {t('page.publish.export.unload')}
        </button>

        <button
          type="button"
          onClick={copyRecord}
          className="inline-flex h-9 w-full items-center justify-center gap-1.5 rounded-lg border border-white/10 px-3.5 text-xs font-semibold text-gray-300 transition-colors hover:border-cyan-500/40 hover:bg-cyan-500/10 hover:text-cyan-300 focus-ring"
        >
          {copied ? <Check size={13} aria-hidden="true" /> : <Copy size={13} aria-hidden="true" />}
          {copied ? t('page.publish.export.copied') : t('page.publish.export.copy')}
        </button>
      </div>

      {blocked && (
        <p className="mt-2.5 text-[11px] leading-snug text-gray-500">
          {t('page.publish.export.blocked')}
        </p>
      )}

      {failedNames.length > 0 && (
        <p className="mt-2.5 flex items-start gap-1.5 text-[11px] leading-snug text-amber-300">
          <AlertTriangle size={13} className="mt-px flex-shrink-0" aria-hidden="true" />
          <span>{t('page.publish.images.failed', { names: failedNames.join(', ') })}</span>
        </p>
      )}

      {error && (
        <p className="mt-2.5 flex items-start gap-1.5 text-[11px] leading-snug text-red-300">
          <AlertTriangle size={13} className="mt-px flex-shrink-0" aria-hidden="true" />
          <span>{t('page.reporter.widget.failed_to_load')}</span>
        </p>
      )}
    </section>
  );
}
